name = "ComponentModel"
uuid = "4b24ec6f-2e34-4333-9ec3-c9a09eea52b5"  
authors = ["Sipeng Luo <SipengLuo@stu.xjtu.edu.cn>"]
version = "0.1.0"

[deps]
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"

[compat]
julia = "1.11"  # 最低兼容的 Julia 版本
DataFrames = "1.0"
